# Generated by Django 3.2.18 on 2023-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamaskuser',
            name='nonce',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
