# Generated by Django 3.2.18 on 2023-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxchain', '0002_alter_metamaskuser_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('seller', models.CharField(max_length=64)),
                ('end_time', models.DateTimeField()),
                ('seller_deposit', models.BigIntegerField()),
                ('buyer_deposit', models.BigIntegerField()),
            ],
        ),
    ]
