# Generated by Django 3.2.18 on 2023-03-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxchain', '0004_auto_20230321_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=64)),
                ('amount', models.BigIntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxchain.contract')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('auction', 'bidder', 'amount'), name='unique bid'),
        ),
    ]
