# Generated by Django 3.2.18 on 2023-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxchain', '0005_auto_20230329_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='open', max_length=64),
        ),
    ]
