# Generated by Django 3.2.18 on 2023-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxchain', '0006_auto_20230329_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image_url',
            field=models.CharField(default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-1-scaled.png', max_length=2048),
        ),
    ]
